inventory/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path("", include("stock.urls")),
    path("admin/", admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stock/urls.py
from django.urls import path, include

from . import views

app_name = "stock"

urlpatterns = [
    path("", views.product_list, name="product_list"),
    path("product/<str:code>/", views.product_detail, name="product_detail"),
    path("search/", views.search, name="search"),
]

stock/models.py
from django.db import models
from django.urls import reverse
from .utils import code_generator

CODE_LENGTH = 6


class Product(models.Model):
    code = models.CharField(max_length=6, unique=True, blank=True)
    name = models.CharField(max_length=50)
    description = models.CharField(max_length=500)
    brand = models.CharField(max_length=250)
    model = models.CharField(max_length=50)
    image = models.ImageField(blank=True)

    class Meta:
        ordering = ("name",)
        indexes = [models.Index(fields=["name"])]

    def __str__(self) -> str:
        return self.name

    def save(self, *args, **kwargs) -> None:
        if not self.code:
            code = code_generator(CODE_LENGTH)
            codes = Product.objects.values_list("code", flat=True)
            while code in codes:
                code = code_generator(CODE_LENGTH)
            self.code = code
        return super(Product, self).save(*args, **kwargs)



class Location(models.Model):
    name = models.CharField(max_length=50)
    slug = models.SlugField(max_length=100)
    description = models.CharField(max_length=500)

    class Meta:
        ordering = ("name",)
        indexes = [models.Index(fields=["name"])]

    def __str__(self) -> str:
        return self.slug


class Item(models.Model):
    code = models.CharField(max_length=6, unique=True, blank=True)
    serial = models.CharField(max_length=50, unique=True)
    product = models.ForeignKey(Product, on_delete=models.CASCADE, related_name="items")
    location = models.ForeignKey(
        Location, on_delete=models.CASCADE, related_name="location"
    )

    def save(self, *args, **kwargs) -> None:
        if not self.code:
            code = code_generator(CODE_LENGTH)
            codes = Item.objects.values_list("code", flat=True)
            while code in codes:
                code = code_generator(CODE_LENGTH)
            self.code = code
        return super(Item, self).save(*args, **kwargs)

    def __str__(self) -> str:
        return self.code

    def get_absolute_url(self):
        return reverse("stock:product_detail", kwargs=dict(code=self.product.code))

stock/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpRequest, HttpResponse
from django.core.paginator import Paginator
from .models import Product, Item, Location
from django.db.models import Q


def product_list(request: HttpRequest) -> HttpResponse:
    products = Product.objects.all()
    items = Item.objects.select_related("product", "location").all()
    paginator = Paginator(items, 5)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    return render(
        request,
        "product_list.html",
        dict(products=products, items=items, page_obj=page_obj),
    )


def product_detail(request: HttpRequest, code: str) -> HttpResponse:
    # product = Product.objects.get(code=code)
    product = get_object_or_404(Product, code=code)
    items = Item.objects.filter(product=product)
    return render(request, "product_detail.html", dict(product=product, items=items))


def location_detail(request: HttpRequest, pk: int) -> HttpResponse:
    location = Location.objects.get(pk=pk)
    items = Item.objects.filter(location=location)
    return render(request, "location_detail.html", dict(location=location, items=items))


def item_detail(request: HttpRequest, pk: int) -> HttpResponse:
    item = Item.objects.get(pk=pk)
    return render(request, "item_detail.html", dict(item=item))


def search(request: HttpRequest) -> HttpResponse:
    query = request.GET.get("input", "")
    print("Query:", query)
    # items = Item.objects.select_related("product", "location").filter(product__name__icontains=query)
    products = Product.objects.filter(name__icontains=query)
    # print("SQL Query:", str(items.query))
    return render(request, "search.html", dict(products=products, query=query))

stock/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link href="{% static 'css/style.css' %}" rel="stylesheet" />
    <title>{% block title %}{% endblock %}</title>
  </head>
  <body>
    <div class="container">
      {% block content %} {% endblock %}
    </div>
  </body>
</html>

stock/templates/index.html
{% extends "base.html" %}
{% block title %}Index{% endblock %}
{% block content%}
<table>
    <thead>
    <tr>
        <th>Code</th>
        <th>Name</th>
        <th>Description</th>
        <th>Brand</th>
        <th>Model</th>
        <th>Image</th>
    </tr>
    </thead>
    <tbody>
        {% for product in products %}
        <tr>
            <td>{{ product.code }}</td>
            <td>{{ product.name }}</td>
            <td>{{ product.description }}</td>
            <td>{{ product.brand }}</td>
            <td>{{ product.model }}</td>
            <td>{{ product.image }}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock %}

stock/templates/inventory.html
{% extends "base.html" %}
{% load thumbnail %}
{% load static %}
{% block title %}Inventory{% endblock %}
{% block content %}
<h1>Inventory</h1>
<div class="search-container">
  <input type="text" class="search-input" placeholder="" />
  <button type="button" class="search-button">
    <span class="loupe">🔍</span>
  </button>
</div>
<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Brand</th>
      <th>Model</th>
      <th>Location</th>
      <th>Serial</th>
      <th>Image</th>
    </tr>
  </thead>
  <tbody>
    {% for item in page_obj %}
    <tr>
      <td>{{ item.code }}</td>
      <td>{{ item.product.name }}</td>
      <td>{{ item.product.brand }}</td>
      <td>{{ item.product.model }}</td>
      <td>{{ item.location.name }}</td>
      <td>{{ item.serial }}</td>
      <td class="td-image">
        <img {% if item.product.image %} src="{% thumbnail item.product.image 180x180 %}" {% else %} src="{% static "img/default_image.png" %}" {% endif %} class="default-img" alt="product image" />
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Página {{ page_obj.number }} de {{ page_obj.paginator.num_pages }}.
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>

{% endblock %}

stock/templates/product_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% load static %}
{% block title %}Product Detail{% endblock %}
{% block content %}
<div class="title-detail">
    <h1>Product: {{ product.code }}</h1>
</div>
<div class="my-row-detail">
    <div>
        <img class="td-image" src="{% thumbnail product.image 300x300 %}" alt="teacher image">
    </div>
    <div>
        <p>
           Name: {{ product.name }}
        </p>

        <p>
            Description: {{ product.description }}
        </p>
        <p>
            Brand: {{ product.brand }}
        </p>
        <p>
            Model: {{ product.model }}
        </p>
        <p>
            Items:
            {% for item in items %}
                {{ item.code }}
            {% endfor %}
        </p>
        <p>
            Location:
            {% for item in items %}
                {{ item.location }}
            {% endfor %}
        </p>
    </div>
</div>
{% endblock %}

stock/templates/product_list.html
{% extends "base.html" %}
{% load thumbnail %}
{% load static %}
{% block title %}Products{% endblock %}
{% block content %}
<h1>Inventory</h1>
<div class="search-container">
  <form method="get" action={% url "stock:search" %}>
    <input type="text" class="search-input" name="input" placeholder="Search product..." />
    <button type="submit" class="search-button">
      <span class="loupe">🔍</span>
    </button>
  </form>
</div>
<table>
  <thead>
    <tr>
      <th>Code</th>
      <th>Name</th>
      <th>Brand</th>
      <th>Model</th>
      <th>Location</th>
      <th>Serial</th>
      <th>Image</th>
    </tr>
  </thead>
  <tbody>
    {% for item in page_obj %}
    <tr>
      <td>
        <a href=" {{ item.get_absolute_url }} ">{{ item.code }}</a>
      </td>
      <td>{{ item.product.name }}</td>
      <td>{{ item.product.brand }}</td>
      <td>{{ item.product.model }}</td>
      <td>{{ item.location.name }}</td>
      <td>{{ item.serial }}</td>
      <td class="td-image">
        <img {% if item.product.image %} src="{{ item.product.image.url }}" {% else %} src="{% static "img/default_image.png" %}" {% endif %} class="default-img" alt="product image" />
      </td>
    </tr>
    {% endfor %}
  </tbody>
</table>
<div class="pagination">
  <span class="step-links">
    {% if page_obj.has_previous %}
    <a href="?page=1">&laquo; first</a>
    <a href="?page={{ page_obj.previous_page_number }}">previous</a>
    {% endif %}

    <span class="current">
      Page {{ page_obj.number }} of {{ page_obj.paginator.num_pages }}
    </span>

    {% if page_obj.has_next %}
    <a href="?page={{ page_obj.next_page_number }}">next</a>
    <a href="?page={{ page_obj.paginator.num_pages }}">last &raquo;</a>
    {% endif %}
  </span>
</div>

{% endblock %}

stock/templates/search.html
{% extends "base.html" %}
{% block title %}Search Results{% endblock %}
{% block content %}
  <h1>Search Results for "{{ query }}"</h1>
  {% if products %}
    <ul>
      {% for product in prodcuts %}
        <li>
            {{ product.name }}
        </li>
      {% endfor %}
    </ul>
  {% else %}
    <p>Not found.</p>
  {% endif %}
{% endblock %}